services:
  postgres_db:
    image: postgres:16-alpine
    container_name: production_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: userManagementServiceDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_runtime_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userManagementServiceDB"]
      interval: 5s
      timeout: 5s
      retries: 5

  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: production_web_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy

# This declaration block must sit at the absolute far-left edge of your file!
volumes:
  postgres_runtime_data:
    driver: local
